#!/usr/bin/env bash
python senti_analysis.py \
  --do_train=True \
  --do_predict=True \
  --max_seq_length=200 \
  --train_batch_size=24 \
  --learning_rate=2e-5 \
  --num_train_epochs=0.1 \
  --save_checkpoints_steps=1000 \
  --keep_checkpoint_max=1 \
  --save_summary_steps=100 \
  --classifier='BiGRU' \
  --rnn_layers=1 \
  --output_dir='./data/sentiment/test' \
  --bert_config_file='./data/pretrained_model/roberta_zh_L-24_H-1024_A-16/bert_config.json' \
  --vocab_file='./data/pretrained_model/roberta_zh_L-24_H-1024_A-16/vocab.txt' \
  --init_checkpoint='./data/pretrained_model/roberta_zh_L-24_H-1024_A-16/bert_model.ckpt' \
  --train_dir='tdt_train_mix_balanced.tsv' \
  --test_dir='tdt_test_mix.tsv' \
  --test_checkpoint_path='./data/sentiment/test/model.ckpt'; \
